### ISSUE TITLE
Issue de muestra

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/clases-resueltas#1]
Este es un issue para mostrar como se ven los issues

Esta es la línea sobre la que habla el issue
https://github.com/1022FSNSANCN02ARED/clases-resueltas/blob/eaf00440b83e452c9519afbe74471ad25f2dd13b/.gitignore#L1

Puede haber una sugerencia de código

```
{
     //sugerencia de código
}
```

**Comment by Piarrot** [comment]
Esto ya está resuelto!
